### ISSUE TITLE
draft documentation 

### ISSUE THREAD

**Issue by gbinal** [GSA/public_analytics#21]
It seems like we should probably have a short page of text explaining the project and starting to answer questions we anticipate.  

cc @leahbannon, @konklone

**Comment by konklone** [comment]
I've added the following text to the bottom of our prototype, in consultation with @leahbannon:

------

<p>
This data is from a unified Google Analytics account for US federal government agencies known as the <a href="https://www.digitalgov.gov/services/dap/">Digital Analytics Program</a>.
</p>

<p>
Currently, the Digital Analytics Program collects web traffic from ________ .gov domains out of <a href="https://catalog.data.gov/dataset/gov-domains-api">roughly 1,200 federal agency domains</a> total. This data is not a representative sample of all web traffic to government domains because it only includes agencies that currently participating in the program.
</p>

<p>
This open source project is dedicated to the international public domain, which means that this website and its data are free for you to use without restriction. You can find the <a href="https://github.com/GSA/public_analytics">code for this website</a> and the <a href="https://github.com/18F/analytics-reporter">code behind the data collection</a> on GitHub.
</p>

----

Note the blank there, `_______`, which needs to be filled in with some kind of number -- or we can rephrase to use a %. Either way, it depends on #15.

@leahbannon I adjusted the language slightly -- I removed the wording around "volunteered", because agencies do have an OMB requirement to participate in the DAP. I also linked to Data.gov for `.gov` domains instead of our blog post, since that's the real official place for the dataset. I also removed mention of "the General Services Administration", on the assumption that a very small number of non-fed citizens know what that is. The DAP mention links to their homepage, which should give the necessary context for the program.
